### ISSUE TITLE
内容问题

### ISSUE THREAD

**Issue by YangFong** [febobo/web-interview#297]
此处似乎是重绘吧，我在学习当中，并不确定这一点，请核实一下。

![image](https://user-images.githubusercontent.com/70502828/146108482-46b58514-a770-4805-9e1a-1d7cda29cd59.png)

---

此外，还是希望一篇文章整体的格式保持统一，此处指出缩进与分号

![image](https://user-images.githubusercontent.com/70502828/146108497-8986dea3-1907-4d51-81a7-30d2c4a34b33.png)

**Comment by YangFong** [comment]
其他发现：

![image](https://user-images.githubusercontent.com/70502828/146121675-efcb1576-c12f-4658-89c7-d3b07acfe00c.png)

描述不统一，个人更偏向使用 TypeScript、JavaScript

![image](https://user-images.githubusercontent.com/70502828/146121697-1e15799a-e9f4-464c-9705-1cd96ed117eb.png)

函数大写让人会误解为构造函数

![image](https://user-images.githubusercontent.com/70502828/146121706-4844ad23-5c4b-420d-b6b5-a3b8db403f95.png)
![image](https://user-images.githubusercontent.com/70502828/146121715-69076ae0-534f-44ba-ad59-a132d3b68ebb.png)

**Comment by febobo** [comment]
收到，感谢指正，方便的话可以提pr过来哈
