### ISSUE TITLE
在题目面试官：bind、call、apply 区别？如何实现一个bind?举的例子中好像有一个错误

### ISSUE THREAD

**Issue by myjstyle** [febobo/web-interview#321]
![github](https://user-images.githubusercontent.com/72686950/156958179-91b0c8a5-600c-44d7-b660-3fb5c2250308.png)
这里用
`const name="lucy"`
来定义name，在es6中let和const定义的变量好像不会挂载到window中，改成var是不是更好，
我输出不出来结果

**Comment by myjstyle** [comment]
就是 `setTimeout(obj.say,0); //lucy，this指向window对象` 这个代码，并没有输出 lucy。

**Comment by YangFong** [comment]
恩，此处确实需要使用 `var`，才能迎合注释
