### ISSUE TITLE
Call这里是不是的代码注释是不是写错了

### ISSUE THREAD

**Issue by NaCl-131** [febobo/web-interview#326]
![image](https://user-images.githubusercontent.com/60124911/158345430-cf2fd8dc-1e36-4c3a-b70a-a3e3346e620e.png)
### 应该是参数列表而不是数组吧？

**Comment by febobo** [comment]
感谢指正

**Comment by febobo** [comment]
发现页面有问题, 如果方便可以通过pr来帮助修复哈~__
