### ISSUE TITLE
在题目《面试官：怎么理解回流跟重绘？什么场景下会触发？》描述矛盾

### ISSUE THREAD

**Issue by coderyjw** [febobo/web-interview#328]
**图一；**
<img width="780" alt="image" src="https://user-images.githubusercontent.com/25735823/158731682-062b19fc-cbc0-4149-b7ad-da55918a65fd.png">
**图二**
<img width="864" alt="image" src="https://user-images.githubusercontent.com/25735823/158731780-f5b65127-cbfa-412e-9a39-b754c95fb10b.png">
**问题**
上面说仅仅触发了回流，但是下面又说触发回流一定会出发重绘，
看上面我就有疑问为什么是仅仅触发了回流，应该是仅仅触发重绘吧🧐

**Comment by febobo** [comment]
感谢指正，正确是仅仅触发重绘， 发现页面错误可以通过pr来帮助修复哈
