### ISSUE TITLE
javascript系列>数组的常用方法有哪些>1操作方法中描述错误

### ISSUE THREAD

**Issue by HowToMeetYou** [febobo/web-interview#345]
[#](https://vue3js.cn/interview/JavaScript/array_api.html#includes)includes()
返回要查找的元素在数组中的位置，找到返回true，否则false

应为判断数组中是否包含指定值，包含返回true，否则返回false

**Comment by febobo** [comment]
可以在当前issue下进行讨论，或者方便的时候可以给我们提pr, 比心
