### ISSUE TITLE
Vue是双向数据流吗？

### ISSUE THREAD

**Issue by NaCl-131** [febobo/web-interview#348]
[链接](https://vue3js.cn/interview/vue/vue.html#%E4%BA%94%E3%80%81vue%E5%92%8Creact%E5%AF%B9%E6%AF%94)
Vue似乎是双向绑定、单向数据流吧！
![image](https://user-images.githubusercontent.com/60124911/179132200-45a50c6f-f1f7-4174-aea1-339ddb3c9206.png)

**Comment by Se1ker** [comment]
我感觉你说的是对的，为什么还没修改
